apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-config-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-config
  template:
    metadata:
      labels:
        app: nginx-config
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        env:
        - name: APP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nginx-secret
              key: password
        volumeMounts:
        - name: config
          mountPath: "/etc/nginx/conf.d"
      volumes:
      - name: config
        configMap:
          name: nginx-config
